// @ts-nocheck
// eslint-disable
// This file is generated by create-validator-ts
import Ajv from 'ajv';
import type * as apiTypes from './types';

export const SCHEMA = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "TokenPropertyPermissionValue": {
            "type": "object",
            "properties": {
                "mutable": {
                    "type": "boolean"
                },
                "collectionAdmin": {
                    "type": "boolean"
                },
                "tokenOwner": {
                    "type": "boolean"
                }
            },
            "required": [
                "mutable",
                "collectionAdmin",
                "tokenOwner"
            ],
            "additionalProperties": false
        },
        "Property": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            },
            "required": [
                "key",
                "value"
            ],
            "additionalProperties": false
        },
        "TokenPropertyPermission": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "permission": {
                    "$ref": "#/definitions/TokenPropertyPermissionValue"
                }
            },
            "required": [
                "key",
                "permission"
            ],
            "additionalProperties": false
        },
        "TokenMediaType": {
            "type": "string",
            "enum": [
                "image",
                "video",
                "audio",
                "3d",
                "file",
                "link"
            ]
        },
        "LinkType": {
            "type": "string",
            "enum": [
                "youtube",
                "vimeo",
                "soundcloud",
                "spotify",
                "deezer",
                "tiktok",
                "instagram",
                "twitter",
                "facebook",
                "twitch",
                "dailymotion",
                "mixcloud",
                "figma"
            ]
        },
        "TokenMediaInfo": {
            "type": "object",
            "properties": {
                "type": {
                    "$ref": "#/definitions/TokenMediaType"
                },
                "linkType": {
                    "$ref": "#/definitions/LinkType"
                },
                "title": {
                    "type": "object",
                    "properties": {
                        "_": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "_"
                    ],
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "order": {
                    "type": "number"
                },
                "main": {
                    "type": "boolean"
                },
                "baseUrlKey": {
                    "type": "string"
                },
                "loop": {
                    "type": "boolean"
                },
                "animation": {
                    "type": "boolean"
                },
                "posterFor": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "UniqueCollectionSchemaV2": {
            "type": "object",
            "properties": {
                "schemaName": {
                    "type": "string"
                },
                "schemaVersion": {
                    "type": "string"
                },
                "baseUrl": {
                    "type": "string"
                },
                "ipfsGateways": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "defaultLocale": {
                    "type": "string"
                },
                "defaultPermission": {
                    "$ref": "#/definitions/TokenPropertyPermissionValue"
                },
                "defaultPermissionForPropertyCommon": {
                    "$ref": "#/definitions/TokenPropertyPermissionValue"
                },
                "info": {},
                "cover": {
                    "type": "object",
                    "properties": {
                        "linkType": {
                            "$ref": "#/definitions/LinkType"
                        },
                        "title": {
                            "type": "object",
                            "properties": {
                                "_": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "_"
                            ],
                            "additionalProperties": {
                                "type": "string"
                            }
                        },
                        "baseUrlKey": {
                            "type": "string"
                        },
                        "loop": {
                            "type": "boolean"
                        },
                        "animation": {
                            "type": "boolean"
                        },
                        "url": {
                            "type": "string"
                        },
                        "urlInfix": {
                            "not": {}
                        },
                        "ipfsCid": {
                            "type": "string"
                        }
                    },
                    "additionalProperties": false
                },
                "media": {
                    "type": "object",
                    "properties": {
                        "defaultPermission": {
                            "$ref": "#/definitions/TokenPropertyPermissionValue"
                        },
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "object",
                                "additionalProperties": false,
                                "properties": {
                                    "type": {
                                        "$ref": "#/definitions/TokenMediaType"
                                    },
                                    "customPermission": {
                                        "$ref": "#/definitions/TokenPropertyPermissionValue"
                                    },
                                    "required": {
                                        "type": "boolean"
                                    },
                                    "linkType": {
                                        "$ref": "#/definitions/LinkType"
                                    },
                                    "title": {
                                        "type": "object",
                                        "properties": {
                                            "_": {
                                                "type": "string"
                                            }
                                        },
                                        "required": [
                                            "_"
                                        ],
                                        "additionalProperties": {
                                            "type": "string"
                                        }
                                    },
                                    "order": {
                                        "type": "number"
                                    },
                                    "main": {
                                        "type": "boolean"
                                    },
                                    "baseUrlKey": {
                                        "type": "string"
                                    },
                                    "loop": {
                                        "type": "boolean"
                                    },
                                    "animation": {
                                        "type": "boolean"
                                    },
                                    "posterFor": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "type"
                                ]
                            }
                        }
                    },
                    "required": [
                        "schema"
                    ],
                    "additionalProperties": false
                },
                "attributes": {
                    "type": "object",
                    "properties": {
                        "defaultPermission": {
                            "$ref": "#/definitions/TokenPropertyPermissionValue"
                        },
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "object",
                                "additionalProperties": false,
                                "properties": {
                                    "optional": {
                                        "type": "boolean"
                                    },
                                    "enumValues": {
                                        "type": "object",
                                        "additionalProperties": {
                                            "anyOf": [
                                                {
                                                    "type": "object",
                                                    "additionalProperties": false,
                                                    "properties": {
                                                        "order": {
                                                            "type": "number"
                                                        },
                                                        "_": {
                                                            "type": "number"
                                                        }
                                                    },
                                                    "required": [
                                                        "_"
                                                    ]
                                                },
                                                {
                                                    "type": "object",
                                                    "additionalProperties": {
                                                        "type": "string"
                                                    },
                                                    "properties": {
                                                        "order": {
                                                            "type": "number"
                                                        },
                                                        "_": {
                                                            "type": "string"
                                                        }
                                                    },
                                                    "required": [
                                                        "_"
                                                    ]
                                                }
                                            ]
                                        }
                                    },
                                    "defaultValue": {
                                        "anyOf": [
                                            {
                                                "type": "string"
                                            },
                                            {
                                                "type": "number"
                                            },
                                            {
                                                "type": "object",
                                                "properties": {
                                                    "_": {
                                                        "type": "number"
                                                    }
                                                },
                                                "required": [
                                                    "_"
                                                ],
                                                "additionalProperties": false
                                            },
                                            {
                                                "type": "object",
                                                "properties": {
                                                    "_": {
                                                        "type": "string"
                                                    }
                                                },
                                                "required": [
                                                    "_"
                                                ],
                                                "additionalProperties": {
                                                    "type": "string"
                                                }
                                            },
                                            {
                                                "type": "array",
                                                "items": {
                                                    "anyOf": [
                                                        {
                                                            "type": "string"
                                                        },
                                                        {
                                                            "type": "number"
                                                        },
                                                        {
                                                            "type": "object",
                                                            "properties": {
                                                                "_": {
                                                                    "type": "number"
                                                                }
                                                            },
                                                            "required": [
                                                                "_"
                                                            ],
                                                            "additionalProperties": false
                                                        },
                                                        {
                                                            "type": "object",
                                                            "properties": {
                                                                "_": {
                                                                    "type": "string"
                                                                }
                                                            },
                                                            "required": [
                                                                "_"
                                                            ],
                                                            "additionalProperties": {
                                                                "type": "string"
                                                            }
                                                        }
                                                    ]
                                                }
                                            }
                                        ]
                                    },
                                    "customPermission": {
                                        "$ref": "#/definitions/TokenPropertyPermissionValue"
                                    },
                                    "order": {
                                        "type": "number"
                                    },
                                    "title": {
                                        "type": "object",
                                        "properties": {
                                            "_": {
                                                "type": "string"
                                            }
                                        },
                                        "required": [
                                            "_"
                                        ],
                                        "additionalProperties": {
                                            "type": "string"
                                        }
                                    },
                                    "type": {
                                        "type": "string",
                                        "enum": [
                                            "integer",
                                            "float",
                                            "boolean",
                                            "timestamp",
                                            "string",
                                            "url",
                                            "isoDate",
                                            "time",
                                            "colorRgba",
                                            "colorLch"
                                        ]
                                    },
                                    "array": {
                                        "type": "boolean"
                                    }
                                },
                                "required": [
                                    "title",
                                    "type"
                                ]
                            }
                        }
                    },
                    "required": [
                        "schema"
                    ],
                    "additionalProperties": false
                },
                "royalties": {
                    "type": "object",
                    "properties": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "royaltyVersion": {
                                    "type": "string"
                                },
                                "primary": {
                                    "type": "object",
                                    "properties": {
                                        "addresses": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "number"
                                            }
                                        }
                                    },
                                    "required": [
                                        "addresses"
                                    ],
                                    "additionalProperties": false
                                },
                                "secondary": {
                                    "type": "object",
                                    "properties": {
                                        "addresses": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "number"
                                            }
                                        }
                                    },
                                    "required": [
                                        "addresses"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "required": [
                                "royaltyVersion"
                            ],
                            "additionalProperties": false
                        },
                        "defaultPermission": {
                            "$ref": "#/definitions/TokenPropertyPermissionValue"
                        }
                    },
                    "required": [
                        "schema"
                    ],
                    "additionalProperties": false
                }
            },
            "required": [
                "schemaName",
                "schemaVersion",
                "baseUrl",
                "cover"
            ],
            "additionalProperties": false
        },
        "UniqueTokenV2": {
            "type": "object",
            "properties": {
                "common": {
                    "type": "object",
                    "properties": {
                        "preview": {
                            "type": "object",
                            "properties": {
                                "linkType": {
                                    "$ref": "#/definitions/LinkType"
                                },
                                "title": {
                                    "type": "object",
                                    "properties": {
                                        "_": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "_"
                                    ],
                                    "additionalProperties": {
                                        "type": "string"
                                    }
                                },
                                "baseUrlKey": {
                                    "type": "string"
                                },
                                "loop": {
                                    "type": "boolean"
                                },
                                "animation": {
                                    "type": "boolean"
                                },
                                "url": {
                                    "type": "string"
                                },
                                "urlInfix": {
                                    "not": {}
                                },
                                "ipfsCid": {
                                    "type": "string"
                                }
                            },
                            "additionalProperties": false
                        },
                        "defaultLocale": {
                            "type": "string"
                        },
                        "name": {
                            "type": "object",
                            "properties": {
                                "_": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "_"
                            ],
                            "additionalProperties": {
                                "type": "string"
                            }
                        },
                        "description": {
                            "type": "object",
                            "properties": {
                                "_": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "_"
                            ],
                            "additionalProperties": {
                                "type": "string"
                            }
                        },
                        "info": {},
                        "ERC721TokenURI": {
                            "type": "string"
                        }
                    },
                    "additionalProperties": false
                },
                "media": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "url": {
                                "type": "string"
                            },
                            "urlInfix": {
                                "not": {}
                            },
                            "ipfsCid": {
                                "type": "string"
                            },
                            "type": {
                                "$ref": "#/definitions/TokenMediaType"
                            },
                            "linkType": {
                                "$ref": "#/definitions/LinkType"
                            },
                            "title": {
                                "type": "object",
                                "properties": {
                                    "_": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "_"
                                ],
                                "additionalProperties": {
                                    "type": "string"
                                }
                            },
                            "order": {
                                "type": "number"
                            },
                            "main": {
                                "type": "boolean"
                            },
                            "baseUrlKey": {
                                "type": "string"
                            },
                            "loop": {
                                "type": "boolean"
                            },
                            "animation": {
                                "type": "boolean"
                            },
                            "posterFor": {
                                "type": "string"
                            }
                        }
                    }
                },
                "royalties": {
                    "type": "object",
                    "properties": {
                        "royaltyVersion": {
                            "type": "string"
                        },
                        "primary": {
                            "type": "object",
                            "properties": {
                                "addresses": {
                                    "type": "object",
                                    "additionalProperties": {
                                        "type": "number"
                                    }
                                }
                            },
                            "required": [
                                "addresses"
                            ],
                            "additionalProperties": false
                        },
                        "secondary": {
                            "type": "object",
                            "properties": {
                                "addresses": {
                                    "type": "object",
                                    "additionalProperties": {
                                        "type": "number"
                                    }
                                }
                            },
                            "required": [
                                "addresses"
                            ],
                            "additionalProperties": false
                        }
                    },
                    "required": [
                        "royaltyVersion"
                    ],
                    "additionalProperties": false
                },
                "attributes": {
                    "type": "object",
                    "additionalProperties": {
                        "anyOf": [
                            {
                                "type": "object",
                                "properties": {
                                    "values": {
                                        "type": "array",
                                        "items": {
                                            "anyOf": [
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "_": {
                                                            "type": "number"
                                                        }
                                                    },
                                                    "required": [
                                                        "_"
                                                    ],
                                                    "additionalProperties": false
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "_": {
                                                            "type": "string"
                                                        }
                                                    },
                                                    "required": [
                                                        "_"
                                                    ],
                                                    "additionalProperties": {
                                                        "type": "string"
                                                    }
                                                }
                                            ]
                                        }
                                    },
                                    "enumKeys": {
                                        "type": "array",
                                        "items": {
                                            "type": [
                                                "string",
                                                "number"
                                            ]
                                        }
                                    }
                                },
                                "additionalProperties": false
                            },
                            {
                                "type": "object",
                                "additionalProperties": false,
                                "properties": {
                                    "values": {
                                        "type": "array",
                                        "items": {
                                            "anyOf": [
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "_": {
                                                            "type": "number"
                                                        }
                                                    },
                                                    "required": [
                                                        "_"
                                                    ],
                                                    "additionalProperties": false
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "_": {
                                                            "type": "string"
                                                        }
                                                    },
                                                    "required": [
                                                        "_"
                                                    ],
                                                    "additionalProperties": {
                                                        "type": "string"
                                                    }
                                                }
                                            ]
                                        }
                                    },
                                    "order": {
                                        "type": "number"
                                    },
                                    "title": {
                                        "type": "object",
                                        "properties": {
                                            "_": {
                                                "type": "string"
                                            }
                                        },
                                        "required": [
                                            "_"
                                        ],
                                        "additionalProperties": {
                                            "type": "string"
                                        }
                                    },
                                    "type": {
                                        "type": "string",
                                        "enum": [
                                            "integer",
                                            "float",
                                            "boolean",
                                            "timestamp",
                                            "string",
                                            "url",
                                            "isoDate",
                                            "time",
                                            "colorRgba",
                                            "colorLch"
                                        ]
                                    },
                                    "array": {
                                        "type": "boolean"
                                    }
                                },
                                "required": [
                                    "title",
                                    "type",
                                    "values"
                                ]
                            }
                        ]
                    }
                }
            },
            "required": [
                "media"
            ],
            "additionalProperties": false
        }
    }
};
const ajv = new Ajv({ removeAdditional: true }).addSchema(SCHEMA, "SCHEMA");
export function validateTokenPropertyPermissionValue(payload: unknown): apiTypes.TokenPropertyPermissionValue {
  /** Schema is defined in {@link SCHEMA.definitions.TokenPropertyPermissionValue } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/TokenPropertyPermissionValue");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid TokenPropertyPermissionValue: ' + ajv.errorsText(validator.errors, {dataVar: "TokenPropertyPermissionValue"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isTokenPropertyPermissionValue(payload: unknown): payload is apiTypes.TokenPropertyPermissionValue {
  try {
    validateTokenPropertyPermissionValue(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateProperty(payload: unknown): apiTypes.Property {
  /** Schema is defined in {@link SCHEMA.definitions.Property } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/Property");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid Property: ' + ajv.errorsText(validator.errors, {dataVar: "Property"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isProperty(payload: unknown): payload is apiTypes.Property {
  try {
    validateProperty(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateTokenPropertyPermission(payload: unknown): apiTypes.TokenPropertyPermission {
  /** Schema is defined in {@link SCHEMA.definitions.TokenPropertyPermission } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/TokenPropertyPermission");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid TokenPropertyPermission: ' + ajv.errorsText(validator.errors, {dataVar: "TokenPropertyPermission"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isTokenPropertyPermission(payload: unknown): payload is apiTypes.TokenPropertyPermission {
  try {
    validateTokenPropertyPermission(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateTokenMediaType(payload: unknown): apiTypes.TokenMediaType {
  /** Schema is defined in {@link SCHEMA.definitions.TokenMediaType } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/TokenMediaType");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid TokenMediaType: ' + ajv.errorsText(validator.errors, {dataVar: "TokenMediaType"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isTokenMediaType(payload: unknown): payload is apiTypes.TokenMediaType {
  try {
    validateTokenMediaType(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateLinkType(payload: unknown): apiTypes.LinkType {
  /** Schema is defined in {@link SCHEMA.definitions.LinkType } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/LinkType");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid LinkType: ' + ajv.errorsText(validator.errors, {dataVar: "LinkType"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isLinkType(payload: unknown): payload is apiTypes.LinkType {
  try {
    validateLinkType(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateTokenMediaInfo(payload: unknown): apiTypes.TokenMediaInfo {
  /** Schema is defined in {@link SCHEMA.definitions.TokenMediaInfo } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/TokenMediaInfo");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid TokenMediaInfo: ' + ajv.errorsText(validator.errors, {dataVar: "TokenMediaInfo"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isTokenMediaInfo(payload: unknown): payload is apiTypes.TokenMediaInfo {
  try {
    validateTokenMediaInfo(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateUniqueCollectionSchemaV2(payload: unknown): apiTypes.UniqueCollectionSchemaV2 {
  /** Schema is defined in {@link SCHEMA.definitions.UniqueCollectionSchemaV2 } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/UniqueCollectionSchemaV2");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid UniqueCollectionSchemaV2: ' + ajv.errorsText(validator.errors, {dataVar: "UniqueCollectionSchemaV2"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isUniqueCollectionSchemaV2(payload: unknown): payload is apiTypes.UniqueCollectionSchemaV2 {
  try {
    validateUniqueCollectionSchemaV2(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateUniqueTokenV2(payload: unknown): apiTypes.UniqueTokenV2 {
  /** Schema is defined in {@link SCHEMA.definitions.UniqueTokenV2 } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/UniqueTokenV2");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid UniqueTokenV2: ' + ajv.errorsText(validator.errors, {dataVar: "UniqueTokenV2"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isUniqueTokenV2(payload: unknown): payload is apiTypes.UniqueTokenV2 {
  try {
    validateUniqueTokenV2(payload);
    return true;
  } catch (error) {
    return false;
  }
}
