// @ts-nocheck
// eslint-disable
// This file is generated by create-validator-ts
import Ajv from 'ajv';
import type * as apiTypes from './types';

export const SCHEMA = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "LocalizedStringWithDefault": {
            "type": "object",
            "properties": {
                "_": {
                    "type": "string"
                }
            },
            "required": [
                "_"
            ],
            "additionalProperties": {
                "type": "string"
            }
        },
        "AttributeValue": {
            "anyOf": [
                {
                    "type": "object",
                    "properties": {
                        "order": {
                            "type": "number"
                        },
                        "_": {
                            "type": "number"
                        }
                    },
                    "required": [
                        "_"
                    ]
                },
                {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "properties": {
                        "order": {
                            "type": "number"
                        },
                        "_": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "_"
                    ]
                }
            ]
        },
        "AttributeValues": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/AttributeValue"
            }
        },
        "TokenPropertyPermissionValue": {
            "type": "object",
            "properties": {
                "mutable": {
                    "type": "boolean"
                },
                "collectionAdmin": {
                    "type": "boolean"
                },
                "tokenOwner": {
                    "type": "boolean"
                }
            },
            "required": [
                "mutable",
                "collectionAdmin",
                "tokenOwner"
            ]
        },
        "Property": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            },
            "required": [
                "key",
                "value"
            ]
        },
        "TokenPropertyPermission": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "permission": {
                    "$ref": "#/definitions/TokenPropertyPermissionValue"
                }
            },
            "required": [
                "key",
                "permission"
            ]
        },
        "TokenMediaType": {
            "type": "string",
            "enum": [
                "image",
                "video",
                "audio",
                "3d",
                "file",
                "link"
            ]
        },
        "SubType": {
            "type": "string",
            "enum": [
                "youtube",
                "vimeo",
                "soundcloud",
                "spotify",
                "deezer",
                "tiktok",
                "instagram",
                "twitter",
                "facebook",
                "twitch",
                "dailymotion",
                "mixcloud",
                "figma"
            ]
        },
        "TokenMediaInfo": {
            "type": "object",
            "properties": {
                "type": {
                    "$ref": "#/definitions/TokenMediaType"
                },
                "subType": {
                    "$ref": "#/definitions/SubType"
                },
                "title": {
                    "$ref": "#/definitions/LocalizedStringWithDefault"
                },
                "order": {
                    "type": "number"
                },
                "main": {
                    "type": "boolean"
                },
                "mimeType": {
                    "type": "string"
                },
                "loop": {
                    "type": "boolean"
                },
                "posterFor": {
                    "type": "string"
                }
            },
            "required": [
                "type"
            ]
        },
        "TokenMediaInfoWithUrl": {
            "type": "object",
            "properties": {
                "type": {
                    "$ref": "#/definitions/TokenMediaType"
                },
                "url": {
                    "type": "string"
                },
                "suffix": {
                    "type": "string"
                },
                "subType": {
                    "$ref": "#/definitions/SubType"
                },
                "title": {
                    "$ref": "#/definitions/LocalizedStringWithDefault"
                },
                "order": {
                    "type": "number"
                },
                "main": {
                    "type": "boolean"
                },
                "mimeType": {
                    "type": "string"
                },
                "loop": {
                    "type": "boolean"
                },
                "posterFor": {
                    "type": "string"
                }
            }
        },
        "ImageItem": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "properties": {
                        "_": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "_"
                    ]
                },
                "mimeType": {
                    "type": "string"
                },
                "loop": {
                    "type": "boolean"
                },
                "url": {
                    "type": "string"
                },
                "suffix": {
                    "type": "string"
                }
            }
        },
        "RoyaltyKind": {
            "type": "object",
            "properties": {
                "addresses": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number"
                    }
                }
            },
            "required": [
                "addresses"
            ]
        },
        "RoyaltySchema": {
            "type": "object",
            "properties": {
                "royaltyVersion": {
                    "type": "number"
                },
                "decimals": {
                    "type": "number"
                },
                "primary": {
                    "$ref": "#/definitions/RoyaltyKind"
                },
                "secondary": {
                    "$ref": "#/definitions/RoyaltyKind"
                }
            },
            "required": [
                "royaltyVersion"
            ]
        },
        "UniqueCollectionSchemaV2": {
            "type": "object",
            "properties": {
                "schemaName": {
                    "type": "string"
                },
                "schemaVersion": {
                    "type": "string"
                },
                "baseUrl": {
                    "type": "string"
                },
                "ipfsGateways": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "defaultLocale": {
                    "type": "string"
                },
                "instantiateWith": {
                    "type": "object",
                    "properties": {
                        "defaultPermission": {
                            "$ref": "#/definitions/TokenPropertyPermissionValue"
                        },
                        "propertyCommonPermission": {
                            "$ref": "#/definitions/TokenPropertyPermissionValue"
                        },
                        "allowERC721MetadataTokenURI": {
                            "anyOf": [
                                {
                                    "type": "boolean"
                                },
                                {
                                    "$ref": "#/definitions/TokenPropertyPermissionValue"
                                }
                            ]
                        }
                    }
                },
                "info": {},
                "cover": {
                    "$ref": "#/definitions/ImageItem"
                },
                "media": {
                    "type": "object",
                    "properties": {
                        "permission": {
                            "$ref": "#/definitions/TokenPropertyPermissionValue"
                        },
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "object",
                                "properties": {
                                    "required": {
                                        "type": "boolean"
                                    },
                                    "permission": {
                                        "$ref": "#/definitions/TokenPropertyPermissionValue"
                                    },
                                    "type": {
                                        "$ref": "#/definitions/TokenMediaType"
                                    },
                                    "subType": {
                                        "$ref": "#/definitions/SubType"
                                    },
                                    "title": {
                                        "$ref": "#/definitions/LocalizedStringWithDefault"
                                    },
                                    "order": {
                                        "type": "number"
                                    },
                                    "main": {
                                        "type": "boolean"
                                    },
                                    "mimeType": {
                                        "type": "string"
                                    },
                                    "loop": {
                                        "type": "boolean"
                                    },
                                    "posterFor": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "type"
                                ]
                            }
                        }
                    },
                    "required": [
                        "schema"
                    ]
                },
                "attributes": {
                    "type": "object",
                    "properties": {
                        "permission": {
                            "$ref": "#/definitions/TokenPropertyPermissionValue"
                        },
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "object",
                                "properties": {
                                    "optional": {
                                        "type": "boolean"
                                    },
                                    "enumValues": {
                                        "type": "object",
                                        "additionalProperties": {
                                            "$ref": "#/definitions/AttributeValue"
                                        }
                                    },
                                    "permission": {
                                        "$ref": "#/definitions/TokenPropertyPermissionValue"
                                    },
                                    "order": {
                                        "type": "number"
                                    },
                                    "title": {
                                        "$ref": "#/definitions/LocalizedStringWithDefault"
                                    },
                                    "type": {
                                        "type": "string",
                                        "enum": [
                                            "integer",
                                            "float",
                                            "boolean",
                                            "timestamp",
                                            "string",
                                            "url",
                                            "isoDate",
                                            "time",
                                            "colorRgba",
                                            "colorLch"
                                        ]
                                    },
                                    "single": {
                                        "type": "boolean"
                                    }
                                },
                                "required": [
                                    "title",
                                    "type"
                                ]
                            }
                        }
                    },
                    "required": [
                        "schema"
                    ]
                },
                "royalties": {
                    "type": "object",
                    "properties": {
                        "permission": {
                            "$ref": "#/definitions/TokenPropertyPermissionValue"
                        },
                        "royaltyVersion": {
                            "type": "number"
                        },
                        "decimals": {
                            "type": "number"
                        },
                        "primary": {
                            "$ref": "#/definitions/RoyaltyKind"
                        },
                        "secondary": {
                            "$ref": "#/definitions/RoyaltyKind"
                        }
                    },
                    "required": [
                        "royaltyVersion"
                    ]
                }
            },
            "required": [
                "schemaName",
                "schemaVersion",
                "baseUrl",
                "cover"
            ]
        },
        "UniqueCollectionSchemaV2InCollection": {
            "type": "object",
            "properties": {
                "schemaName": {
                    "type": "string"
                },
                "schemaVersion": {
                    "type": "string"
                },
                "baseUrl": {
                    "type": "string"
                },
                "ipfsGateways": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "defaultLocale": {
                    "type": "string"
                },
                "instantiateWith": {
                    "type": "object",
                    "properties": {
                        "defaultPermission": {
                            "$ref": "#/definitions/TokenPropertyPermissionValue"
                        },
                        "propertyCommonPermission": {
                            "$ref": "#/definitions/TokenPropertyPermissionValue"
                        },
                        "allowERC721MetadataTokenURI": {
                            "anyOf": [
                                {
                                    "type": "boolean"
                                },
                                {
                                    "$ref": "#/definitions/TokenPropertyPermissionValue"
                                }
                            ]
                        }
                    }
                },
                "info": {},
                "cover": {
                    "$ref": "#/definitions/ImageItem"
                },
                "media": {
                    "type": "object",
                    "properties": {
                        "permission": {
                            "$ref": "#/definitions/TokenPropertyPermissionValue"
                        },
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "object",
                                "properties": {
                                    "required": {
                                        "type": "boolean"
                                    },
                                    "permission": {
                                        "$ref": "#/definitions/TokenPropertyPermissionValue"
                                    },
                                    "type": {
                                        "$ref": "#/definitions/TokenMediaType"
                                    },
                                    "subType": {
                                        "$ref": "#/definitions/SubType"
                                    },
                                    "title": {
                                        "$ref": "#/definitions/LocalizedStringWithDefault"
                                    },
                                    "order": {
                                        "type": "number"
                                    },
                                    "main": {
                                        "type": "boolean"
                                    },
                                    "mimeType": {
                                        "type": "string"
                                    },
                                    "loop": {
                                        "type": "boolean"
                                    },
                                    "posterFor": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "type"
                                ]
                            }
                        }
                    },
                    "required": [
                        "schema"
                    ]
                },
                "attributes": {
                    "type": "object",
                    "properties": {
                        "permission": {
                            "$ref": "#/definitions/TokenPropertyPermissionValue"
                        },
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "object",
                                "properties": {
                                    "optional": {
                                        "type": "boolean"
                                    },
                                    "enumValues": {
                                        "type": "object",
                                        "additionalProperties": {
                                            "$ref": "#/definitions/AttributeValue"
                                        }
                                    },
                                    "permission": {
                                        "$ref": "#/definitions/TokenPropertyPermissionValue"
                                    },
                                    "order": {
                                        "type": "number"
                                    },
                                    "title": {
                                        "$ref": "#/definitions/LocalizedStringWithDefault"
                                    },
                                    "type": {
                                        "type": "string",
                                        "enum": [
                                            "integer",
                                            "float",
                                            "boolean",
                                            "timestamp",
                                            "string",
                                            "url",
                                            "isoDate",
                                            "time",
                                            "colorRgba",
                                            "colorLch"
                                        ]
                                    },
                                    "single": {
                                        "type": "boolean"
                                    }
                                },
                                "required": [
                                    "title",
                                    "type"
                                ]
                            }
                        }
                    },
                    "required": [
                        "schema"
                    ]
                },
                "royalties": {
                    "type": "object",
                    "properties": {
                        "permission": {
                            "$ref": "#/definitions/TokenPropertyPermissionValue"
                        },
                        "royaltyVersion": {
                            "type": "number"
                        },
                        "decimals": {
                            "type": "number"
                        },
                        "primary": {
                            "$ref": "#/definitions/RoyaltyKind"
                        },
                        "secondary": {
                            "$ref": "#/definitions/RoyaltyKind"
                        }
                    },
                    "required": [
                        "royaltyVersion"
                    ]
                }
            },
            "required": [
                "baseUrl",
                "cover"
            ]
        },
        "SchemaBasedAttributeInToken": {
            "type": "object",
            "properties": {
                "enumKeys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "values": {
                    "$ref": "#/definitions/AttributeValues"
                }
            }
        },
        "DynamicAttributeInToken": {
            "type": "object",
            "properties": {
                "values": {
                    "$ref": "#/definitions/AttributeValues"
                },
                "order": {
                    "type": "number"
                },
                "title": {
                    "$ref": "#/definitions/LocalizedStringWithDefault"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "integer",
                        "float",
                        "boolean",
                        "timestamp",
                        "string",
                        "url",
                        "isoDate",
                        "time",
                        "colorRgba",
                        "colorLch"
                    ]
                },
                "single": {
                    "type": "boolean"
                }
            },
            "required": [
                "title",
                "type",
                "values"
            ]
        },
        "TokenAttributeItem": {
            "anyOf": [
                {
                    "$ref": "#/definitions/SchemaBasedAttributeInToken"
                },
                {
                    "$ref": "#/definitions/DynamicAttributeInToken"
                }
            ]
        },
        "UniqueTokenV2": {
            "type": "object",
            "properties": {
                "common": {
                    "type": "object",
                    "properties": {
                        "preview": {
                            "$ref": "#/definitions/ImageItem"
                        },
                        "defaultLocale": {
                            "type": "string"
                        },
                        "name": {
                            "$ref": "#/definitions/LocalizedStringWithDefault"
                        },
                        "description": {
                            "$ref": "#/definitions/LocalizedStringWithDefault"
                        },
                        "info": {},
                        "ERC721MetadataTokenURI": {
                            "type": "string"
                        }
                    }
                },
                "media": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/TokenMediaInfoWithUrl"
                    }
                },
                "royalties": {
                    "$ref": "#/definitions/RoyaltySchema"
                },
                "attributes": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/TokenAttributeItem"
                    }
                }
            }
        }
    }
};
const ajv = new Ajv({ removeAdditional: true }).addSchema(SCHEMA, "SCHEMA");
export function validateLocalizedStringWithDefault(payload: unknown): apiTypes.LocalizedStringWithDefault {
  /** Schema is defined in {@link SCHEMA.definitions.LocalizedStringWithDefault } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/LocalizedStringWithDefault");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid LocalizedStringWithDefault: ' + ajv.errorsText(validator.errors, {dataVar: "LocalizedStringWithDefault"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isLocalizedStringWithDefault(payload: unknown): payload is apiTypes.LocalizedStringWithDefault {
  try {
    validateLocalizedStringWithDefault(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateAttributeValue(payload: unknown): apiTypes.AttributeValue {
  /** Schema is defined in {@link SCHEMA.definitions.AttributeValue } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/AttributeValue");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid AttributeValue: ' + ajv.errorsText(validator.errors, {dataVar: "AttributeValue"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isAttributeValue(payload: unknown): payload is apiTypes.AttributeValue {
  try {
    validateAttributeValue(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateAttributeValues(payload: unknown): apiTypes.AttributeValues {
  /** Schema is defined in {@link SCHEMA.definitions.AttributeValues } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/AttributeValues");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid AttributeValues: ' + ajv.errorsText(validator.errors, {dataVar: "AttributeValues"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isAttributeValues(payload: unknown): payload is apiTypes.AttributeValues {
  try {
    validateAttributeValues(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateTokenPropertyPermissionValue(payload: unknown): apiTypes.TokenPropertyPermissionValue {
  /** Schema is defined in {@link SCHEMA.definitions.TokenPropertyPermissionValue } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/TokenPropertyPermissionValue");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid TokenPropertyPermissionValue: ' + ajv.errorsText(validator.errors, {dataVar: "TokenPropertyPermissionValue"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isTokenPropertyPermissionValue(payload: unknown): payload is apiTypes.TokenPropertyPermissionValue {
  try {
    validateTokenPropertyPermissionValue(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateProperty(payload: unknown): apiTypes.Property {
  /** Schema is defined in {@link SCHEMA.definitions.Property } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/Property");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid Property: ' + ajv.errorsText(validator.errors, {dataVar: "Property"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isProperty(payload: unknown): payload is apiTypes.Property {
  try {
    validateProperty(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateTokenPropertyPermission(payload: unknown): apiTypes.TokenPropertyPermission {
  /** Schema is defined in {@link SCHEMA.definitions.TokenPropertyPermission } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/TokenPropertyPermission");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid TokenPropertyPermission: ' + ajv.errorsText(validator.errors, {dataVar: "TokenPropertyPermission"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isTokenPropertyPermission(payload: unknown): payload is apiTypes.TokenPropertyPermission {
  try {
    validateTokenPropertyPermission(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateTokenMediaType(payload: unknown): apiTypes.TokenMediaType {
  /** Schema is defined in {@link SCHEMA.definitions.TokenMediaType } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/TokenMediaType");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid TokenMediaType: ' + ajv.errorsText(validator.errors, {dataVar: "TokenMediaType"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isTokenMediaType(payload: unknown): payload is apiTypes.TokenMediaType {
  try {
    validateTokenMediaType(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateSubType(payload: unknown): apiTypes.SubType {
  /** Schema is defined in {@link SCHEMA.definitions.SubType } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/SubType");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid SubType: ' + ajv.errorsText(validator.errors, {dataVar: "SubType"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isSubType(payload: unknown): payload is apiTypes.SubType {
  try {
    validateSubType(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateTokenMediaInfo(payload: unknown): apiTypes.TokenMediaInfo {
  /** Schema is defined in {@link SCHEMA.definitions.TokenMediaInfo } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/TokenMediaInfo");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid TokenMediaInfo: ' + ajv.errorsText(validator.errors, {dataVar: "TokenMediaInfo"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isTokenMediaInfo(payload: unknown): payload is apiTypes.TokenMediaInfo {
  try {
    validateTokenMediaInfo(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateTokenMediaInfoWithUrl(payload: unknown): apiTypes.TokenMediaInfoWithUrl {
  /** Schema is defined in {@link SCHEMA.definitions.TokenMediaInfoWithUrl } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/TokenMediaInfoWithUrl");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid TokenMediaInfoWithUrl: ' + ajv.errorsText(validator.errors, {dataVar: "TokenMediaInfoWithUrl"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isTokenMediaInfoWithUrl(payload: unknown): payload is apiTypes.TokenMediaInfoWithUrl {
  try {
    validateTokenMediaInfoWithUrl(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateImageItem(payload: unknown): apiTypes.ImageItem {
  /** Schema is defined in {@link SCHEMA.definitions.ImageItem } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/ImageItem");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid ImageItem: ' + ajv.errorsText(validator.errors, {dataVar: "ImageItem"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isImageItem(payload: unknown): payload is apiTypes.ImageItem {
  try {
    validateImageItem(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateRoyaltyKind(payload: unknown): apiTypes.RoyaltyKind {
  /** Schema is defined in {@link SCHEMA.definitions.RoyaltyKind } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/RoyaltyKind");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid RoyaltyKind: ' + ajv.errorsText(validator.errors, {dataVar: "RoyaltyKind"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isRoyaltyKind(payload: unknown): payload is apiTypes.RoyaltyKind {
  try {
    validateRoyaltyKind(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateRoyaltySchema(payload: unknown): apiTypes.RoyaltySchema {
  /** Schema is defined in {@link SCHEMA.definitions.RoyaltySchema } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/RoyaltySchema");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid RoyaltySchema: ' + ajv.errorsText(validator.errors, {dataVar: "RoyaltySchema"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isRoyaltySchema(payload: unknown): payload is apiTypes.RoyaltySchema {
  try {
    validateRoyaltySchema(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateUniqueCollectionSchemaV2(payload: unknown): apiTypes.UniqueCollectionSchemaV2 {
  /** Schema is defined in {@link SCHEMA.definitions.UniqueCollectionSchemaV2 } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/UniqueCollectionSchemaV2");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid UniqueCollectionSchemaV2: ' + ajv.errorsText(validator.errors, {dataVar: "UniqueCollectionSchemaV2"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isUniqueCollectionSchemaV2(payload: unknown): payload is apiTypes.UniqueCollectionSchemaV2 {
  try {
    validateUniqueCollectionSchemaV2(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateUniqueCollectionSchemaV2InCollection(payload: unknown): apiTypes.UniqueCollectionSchemaV2InCollection {
  /** Schema is defined in {@link SCHEMA.definitions.UniqueCollectionSchemaV2InCollection } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/UniqueCollectionSchemaV2InCollection");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid UniqueCollectionSchemaV2InCollection: ' + ajv.errorsText(validator.errors, {dataVar: "UniqueCollectionSchemaV2InCollection"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isUniqueCollectionSchemaV2InCollection(payload: unknown): payload is apiTypes.UniqueCollectionSchemaV2InCollection {
  try {
    validateUniqueCollectionSchemaV2InCollection(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateSchemaBasedAttributeInToken(payload: unknown): apiTypes.SchemaBasedAttributeInToken {
  /** Schema is defined in {@link SCHEMA.definitions.SchemaBasedAttributeInToken } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/SchemaBasedAttributeInToken");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid SchemaBasedAttributeInToken: ' + ajv.errorsText(validator.errors, {dataVar: "SchemaBasedAttributeInToken"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isSchemaBasedAttributeInToken(payload: unknown): payload is apiTypes.SchemaBasedAttributeInToken {
  try {
    validateSchemaBasedAttributeInToken(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateDynamicAttributeInToken(payload: unknown): apiTypes.DynamicAttributeInToken {
  /** Schema is defined in {@link SCHEMA.definitions.DynamicAttributeInToken } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/DynamicAttributeInToken");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid DynamicAttributeInToken: ' + ajv.errorsText(validator.errors, {dataVar: "DynamicAttributeInToken"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isDynamicAttributeInToken(payload: unknown): payload is apiTypes.DynamicAttributeInToken {
  try {
    validateDynamicAttributeInToken(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateTokenAttributeItem(payload: unknown): apiTypes.TokenAttributeItem {
  /** Schema is defined in {@link SCHEMA.definitions.TokenAttributeItem } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/TokenAttributeItem");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid TokenAttributeItem: ' + ajv.errorsText(validator.errors, {dataVar: "TokenAttributeItem"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isTokenAttributeItem(payload: unknown): payload is apiTypes.TokenAttributeItem {
  try {
    validateTokenAttributeItem(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateUniqueTokenV2(payload: unknown): apiTypes.UniqueTokenV2 {
  /** Schema is defined in {@link SCHEMA.definitions.UniqueTokenV2 } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/UniqueTokenV2");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid UniqueTokenV2: ' + ajv.errorsText(validator.errors, {dataVar: "UniqueTokenV2"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isUniqueTokenV2(payload: unknown): payload is apiTypes.UniqueTokenV2 {
  try {
    validateUniqueTokenV2(payload);
    return true;
  } catch (error) {
    return false;
  }
}
